services:
  - type: web
    name: attrition-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    plan: free
    pythonVersion: 3.11.9
